project/urls.py
from ninja import NinjaAPI
from user.api import router as user_router

api = NinjaAPI()

api.add_router("/events/", user_router)


from django.contrib import admin
from django.urls import path, include
from django.views.csrf import csrf_failure

handler403 = csrf_failure

urlpatterns = [
    path('', include('reports.urls', namespace='reports')),
    path('api/', api.urls, name='api'),

    path('user/', include('user.urls')),
    path('admin/',   admin.site.urls),
]

reports/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (report_create_view, get_attack_types_for_chart, ReportListView, ReportDetailView, MonthlyReportView, \
    export_monthly_reports, ReportDownloadView, get_static_analytic_file, analytics_view, get_risk_assessments_reports,
                    get_countries_attacks, get_departments, get_ip_count)

app_name = 'reports'   # опционально, но удобно для именованных маршрутов

urlpatterns = [
    path('',       report_create_view, name='report_new'),
    path('list/',      ReportListView.as_view(),   name='report_list'),
    path('<int:pk>/',  ReportDetailView.as_view(), name='report_detail'),
    path('get_departments/', get_departments, name='departments'),
    path('analytics/', analytics_view,     name='report_analytics'),
    path('analytics-attack-types/', get_attack_types_for_chart, name='report_analytics_attacks'),
    path('analytics-risc-assessments/', get_risk_assessments_reports, name='attack_risc'),
    path('analytics-country-attacks/', get_countries_attacks, name='countries_attacks'),
    path('analytics-static-reports/', get_static_analytic_file, name='static_reports'),
    path('analytics-ip-counts/', get_ip_count, name='get_ip_count'),
    path('monthly/', MonthlyReportView.as_view(), name='report_monthly'),
    path('monthly/export/', export_monthly_reports, name='report_monthly_export'),
    path('download/<int:pk>/', ReportDownloadView.as_view(), name='report_pdf'),
]

user/urls.py
from . import views
from django.urls import path

app_name = 'user'

urlpatterns = [
    path('login/', views.user_login_view, name='login'),
    path('logout/', views.user_logout_view, name='logout'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}SOC Reports{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

  <!-- Глобальные стили для всех таблиц -->
  <style>
    table {
      width: 100%;
      border-collapse: collapse;
    }
    table, th, td {
      border: 1px solid #dee2e6;
    }
    th, td {
      padding: 0.5rem;
    }

    .enter-link {
      color: white;
      display: inline-block;
      text-decoration: none;
    }

  </style>
</head>
<body>
  <!-- Flash-уведомления -->
  {% if messages %}
    <div class="position-fixed top-0 end-0 p-3" style="z-index:2000;">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class=" container container-fluid">
      <a class="navbar-brand" href="{% url 'reports:report_new' %}">SOC Reports</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'report_new' %}active{% endif %}"
               href="{% url 'reports:report_new' %}">
              Новый отчет
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'report_list' %}active{% endif %}"
               href="{% url 'reports:report_list' %}">
              Список отчетов
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'report_analytics' %}active{% endif %}"
               href="{% url 'reports:report_analytics' %}">
              Аналитика
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'report_monthly' %}active{% endif %}"
               href="{% url 'reports:report_monthly' %}">
              Ежемесячные отчеты
            </a>
          </li>
        </ul>
      </div>

      {% if request.user.is_authenticated %}
        <a class="enter-link" href="{% url 'user:logout' %}">Выход</a>
      {% else %}
        <a class="enter-link" href="{% url 'user:login' %}">Вход</a>
      {% endif %}
    </div>

  </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

  {% block scripts %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</body>
</html>